version: "3.3"

services:

  api:
    build:
      context: .
    image: microservices
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal


  posts:
    build:
      context: .
    image: microservices
    env_file: docker-compose.env
    environment:
      SERVICES: posts
    depends_on:
      - nats
    networks:
      - internal

  comments:
    build:
      context: .
    image: microservices
    env_file: docker-compose.env
    environment:
      SERVICES: comments
    depends_on:
      - nats
    networks:
      - internal


  query:
    build:
      context: .
    image: microservices
    env_file: docker-compose.env
    environment:
      SERVICES: query
    depends_on:
      - nats
    networks:
      - internal
  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
